### ISSUE TITLE
Postion scoped to optional association

### ISSUE THREAD

**Issue by armchairdj** [brendon/acts_as_list#444]
Thanks for maintaining this gem. I've been using it for like a decade!

I have a `Post` model. It optionally belongs_to `Series`. When a series is present, I want `position` to be calculated within the series. When a series is not present, I want `position` to be nil.

However, all of my series-free posts seem to be scoped to the `nil` series_id and their positions are calculated as if that's a valid series.

Short of monkey-patching, I'm not sure how to get what I want. These values aren't really hurting anything, but it's annoying that a bunch of extra DB work is happening on every save when it doesn't need to.

I've considered moving the series association to a join table but it's not a many-to-many so I'd be contorting my database and making my queries more expensive and annoying to maintain just to get what seems like a really simple and common desired behavior.

Am I missing something?

I looked into switching to the `positioning` gem, but that doesn't seem to have this feature, either. In fact it recommends that all `position` columns have a not-null constraint.

**Comment by brendon** [comment]
Hi @armchairdj, unfortunately you're correct on both counts and when I've looked at how to do this it always ends up hard and hackey.

The problem is how to describe what's in the list and what isn't. Your case is simple but it opens up the door to lots of other cases with more complex descriptions. At the end of the day I'm hoping the DB overhead (at least from `positioning`) isn't going to be a material issue. If it does cause a noticeable slowdown at scale please let me know. If you're just adding to the end of the list then the queries that move things out of the way basically do nothing anyway.

In my application I have a scenario like yours, but I actually want my items ordered when they don't have the optional parent.

If you think there's a way to do this in a tidy way (in `positioning`) then perhaps put a bit of a PR proof of concept together over there. It will need to be flexible though :)
